### ISSUE TITLE
Cannot import PyNanoInstantMeshes

### ISSUE THREAD

**Issue by shschong** [vork/PyNanoInstantMeshes#5]
Traceback (most recent call last):
  File "C:\Users\User\Documents\ComfyUI\ComfyUI-Easy-Install-EP24\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Documents\\ComfyUI\\ComfyUI-Easy-Install-EP24\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\PyNanoInstantMeshes\\__init__.py'

Cannot import C:\Users\User\Documents\ComfyUI\ComfyUI-Easy-Install-EP24\ComfyUI_windows_portable\ComfyUI\custom_nodes\PyNanoInstantMeshes module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\User\\Documents\\ComfyUI\\ComfyUI-Easy-Install-EP24\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\PyNanoInstantMeshes\\__init__.py'

Update:
init.py is supposed to have underscores. I don't know why github is not showing the underscores.

**Comment by shschong** [comment]
I installed pynim
